# Generated by Django 4.1.7 on 2023-03-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("profile", models.TextField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("skills", models.CharField(max_length=255)),
                ("resume", models.FileField(upload_to="resumes/")),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=20)),
                ("jobs_completed", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
